### ISSUE TITLE
what

### ISSUE THREAD

**Issue by RacoonDog** [CunnyDevelopment/CunnyAddon#1]
is this

**Comment by ViaTi** [comment]
It's a meteor add-on that auto renames modules for compatibility along with saying what addon modules are from, it also allows patch files to change categories, names, and module visibility using class names.

**Comment by RacoonDog** [comment]
> It's a meteor add-on that auto renames modules for compatibility along with saying what addon modules are from, it also allows patch files to change categories, names, and module visibility using class names.

ok

**Comment by RacoonDog** [comment]
i absolutely need to get into contact with whoever the fuck made this
Crosby#9153
